#!/usr/bin/env python3

import os

s = """{
  "controller": {
    "hosts": [
      "%s"
    ]
  },
  "_meta": {
    "hostvars": {
      "%s": {
        "ansible_connection": "local"
      }
    }
  }
}"""

hostname = os.getenv('HOSTNAME')
print(s % (hostname, hostname))
