---

dconf_configuration:

  "/org/gnome/shell/enabled-extensions": >-
    ['apps-menu@gnome-shell-extensions.gcampax.github.com',
    'desktop-icons@gnome-shell-extensions.gcampax.github.com',
    'places-menu@gnome-shell-extensions.gcampax.github.com',
    'window-list@gnome-shell-extensions.gcampax.github.com',
    'appindicatorsupport@rgcjonas.gmail.com',
    'vertical-workspaces@G-dH.github.com',
    'launch-new-instance@gnome-shell-extensions.gcampax.github.com',
    'sound-output-device-chooser@kgshank.net']

  "/org/gnome/shell/favorite-apps": >-
    ['firefox.desktop',
    'chromium-browser.desktop',
    'org.gnome.Terminal.desktop',
    'org.gnome.Screenshot.desktop',
    'org.qgis.qgis.desktop',
    'com.discordapp.Discord.desktop']

  "/org/gnome/desktop/wm/preferences/button-layout": "'appmenu:minimize,maximize,close'"
  
  "/org/gnome/desktop/privacy/remember-recent-files": "false"
  
  "/org/gnome/desktop/session/idle-delay": "uint32 0"
  
  "/org/gnome/desktop/peripherals/touchpad/tap-to-click": "true"
  
  "/org/gnome/shell/extensions/desktop-icons/icon-size": "'small'"

  "/org/gnome/shell/extensions/desktop-icons/show-home": "false"
  
  "/org/gnome/desktop/screensaver/lock-enabled": "false"
  
  "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type": "'nothing'"
  
  "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout": "3600"
  
  "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type": "'nothing'"
  
  "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout": "1800"
  
  "/org/gnome/settings-daemon/plugins/media-keys/max-screencast-length": "uint32 0"

  "/org/gnome/shell/extensions/vertical-workspaces/show-search-entry": "true"

  "/org/gnome/shell/extensions/vertical-workspaces/center-search": "true"

  "/org/gnome/shell/extensions/vertical-workspaces/dash-position": "3"

  "/org/gnome/shell/extensions/vertical-workspaces/dash-max-icon-size": "3"

  "/org/gnome/shell/extensions/vertical-workspaces/show-app-icon-position": "1"

  "/org/gnome/shell/extensions/vertical-workspaces/show-ws-preview-bg": "false"

